name: ADCCLA
favicon: null
layout_spectrum: 0.91888
typography_spectrum: 0.04392
title: Arts District Community Council LA - Change begins with one small action
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.875
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
