name: ADCCLA
favicon: null
layout_spectrum: 0.84664
typography_spectrum: 0.04392
title: Arts District Community Council LA - Change begins with one small action
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e252f'
    - '#d74840'
    - '#edd5ce'
    - '#dca6a2'
    - '#741a1a'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
